[default]
src = 'packages/contracts/src'
test = 'packages/contracts/test'
out = 'packages/contracts/out'
cache_path = 'packages/contracts/cache'
libs = ['packages/contracts/lib']
verbosity = 2
# Foundry is fast enough that we can ignore the cache for now
force = false
bytecode_hash = 'none'
solc_version = '0.8.13'
extra_output_files = ['abi']
